spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: http://patient-service
          predicates:
            - Path=/patient/**
          filters:
            - RewritePath=/path/(?<path>.*), /$\{path}
        - id: practitioner-service
          uri: http://practitioner-service
          predicates:
            - Path=/practitioner/**
          filters:
            - RewritePath=/path/(?<path>.*), /$\{path}
        - id: encounter-service
          uri: http://encounter-service
          predicates:
            - Path=/encounter/**
          filters:
            - RewritePath=/path/(?<path>.*), /$\{path}
