spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: http://patient-service:8089
          predicates:
            - Path=/patient/**
          filters:
            - RewritePath=/path/(?<path>.*), /$\{path}
        - id: practitioner-service
          uri: http://practitioner-service:8088
          predicates:
            - Path=/practitioner/**
          filters:
            - RewritePath=/path/(?<path>.*), /$\{path}
        - id: encounter-service
          uri: http://encounter-service:8087
          predicates:
            - Path=/encounter/**
          filters:
            - RewritePath=/path/(?<path>.*), /$\{path}
